M48
; DRILL file {KiCad 9.0.5} date 2025-10-23T20:31:54+1300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-23T20:31:54+13:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.100
%
G90
G05
T1
X67.814Y-60.627
T2
X66.314Y-65.707
M30
