M48
; DRILL file {KiCad 9.0.6} date 2026-01-30T18:58:32+1300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-30T18:58:32+13:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.100
%
G90
G05
T1
X67.67Y-83.305
T2
X66.17Y-78.225
M30
